name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run install_dependencies script
        run: |
          chmod +x firmware/scripts/install_dependencies.sh
          ./firmware/scripts/install_dependencies.sh

      
      - name: Compile Firmware (receiver)
        run: |
          cd ./firmware/receiver
          sudo /root/.platformio/penv/bin/platformio run

      - name: Compile Firmware (turntable)
        run: |
          cd ./firmware/turntable
          sudo /root/.platformio/penv/bin/platformio run