name: Arduino CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download Arduino CLI
      run: |
        cd firmware
        wget https://downloads.arduino.cc/arduino-cli/arduino-cli_latest_Linux_64bit.tar.gz
        tar -xvf arduino-cli_latest_Linux_64bit.tar.gz
        chmod +x arduino-cli

    - name: Set up Arduino CLI
      run: |
        cd firmware
        ./arduino-cli config init

    - name: Install ESP32 core
      run: |
        cd firmware
        ./arduino-cli core update-index
        ./arduino-cli core install esp32:esp32

    - name: Install Libraries from arduino-cli.yaml
      run: |
        cd firmware
        ./arduino-cli lib install --json-file arduino-cli.yaml

    - name: Compile Arduino Sketch for ESP32-S2 Mini
      run: |
        cd firmware
        ./arduino-cli compile --fqbn esp32:esp32:lolin_s2_mini firmware.ino
