name: Arduino CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Arduino CLI
      run: |
        wget https://downloads.arduino.cc/arduino-cli/arduino-cli_latest_Linux_64bit.tar.gz
        tar -xvf arduino-cli_latest_Linux_64bit.tar.gz
        sudo mv arduino-cli /usr/local/bin/
        arduino-cli config init

    - name: Install ESP32 core
      run: |
        arduino-cli core update-index
        arduino-cli core install esp32:esp32

    - name: Compile Arduino Sketch for ESP32-S2 Mini
      run: |
        arduino-cli compile --fqbn esp32:esp32:lolin_s2_mini firmware/firmware.ino
