name: Arduino CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Arduino CLI
      run: |
        cd firmware
        chmod +x arduino-cli
        ./arduino-cli config init

    - name: Install ESP32 core
      run: |
        cd firmware
        ./arduino-cli core update-index
        ./arduino-cli core install esp32:esp32

    - name: Install Libraries
      run: |
        cd firmware
        ./arduino-cli lib install "Adafruit Unified Sensor" # Replace with your library
        ./arduino-cli lib install "Another Library" # Add more libraries as needed

    - name: Compile Arduino Sketch for ESP32-S2 Mini
      run: |
        cd firmware
        ./arduino-cli compile --fqbn esp32:esp32:lolin_s2_mini firmware.ino
